## NumPy 百题大冲关

---

#### 介绍

NumPy 是 Python 语言的一个第三方库，其支持大量高维度数组与矩阵运算。此外，NumPy 也针对数组运算提供大量的数学函数。机器学习涉及到大量对数组的变换和运算，NumPy 就成了必不可少的工具之一。NumPy 百题大冲关分为基础篇和进阶篇，每部分各有 50 道练习题。基础部分的练习题在于熟悉 NumPy 常用方法的使用，而进阶部分则侧重于 NumPy 方法的组合应用。

---

### 基础部分

练习 NumPy 之前，首先需要导入 NumPy 模块，并约定简称为 `np`。

**1. 导入 NumPy：**

In [1]:
import numpy as np

**2. 查看 NumPy 版本信息：**

In [2]:
np.__version__

'1.21.3'

### 创建数组

NumPy 的主要对象是多维数组 Ndarray。在 NumPy 中维度 Dimensions 叫做轴 Axes，轴的个数叫做秩 Rank。注意，`numpy.array` 和 Python 标准库 `array.array` 并不相同，前者更为强大，这也就是我们学习 NumPy 的重要原因之一。

**3. 通过列表创建一维数组：**

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

方数组是一个秩为 1 的数组，因为它只有一个轴，而轴的长度为 3。

**4. 通过列表创建二维数组：**

In [4]:
np.array([(1, 2, 3), (4, 5, 6)])

array([[1, 2, 3],
       [4, 5, 6]])

上方数组的秩为 2。第一个维度长度为 2,第二个维度长度为 3。

**5. 创建全为 0 的二维数组：**

In [5]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**6. 创建全为 1 的三维数组：**

In [6]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

**7. 创建一维等差数组：**

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

**8. 创建二维等差数组：**

In [8]:
np.arange(6).reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

**9. 创建单位矩阵（二维数组）：**

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**10. 创建等间隔一维数组：**

In [10]:
np.linspace(1, 10, num=6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

**11. 创建二维随机数组：**

In [11]:
np.random.rand(2, 3)

array([[0.83575664, 0.4545927 , 0.56924018],
       [0.2791887 , 0.78604405, 0.90210658]])

12. 创建二维随机整数数组（数值小于 5）：

In [12]:
np.random.randint(5, size=(2, 3))

array([[4, 3, 3],
       [1, 1, 3]])

**13. 依据自定义函数创建数组：**

In [13]:
np.fromfunction(lambda i, j: i + j, (3, 3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

### 数组运算

**生成一维示例数组：**

In [14]:
a = np.array([10, 20, 30, 40, 50])
b = np.arange(1, 6)
a, b

(array([10, 20, 30, 40, 50]), array([1, 2, 3, 4, 5]))

**14. 一维数组加法运算：**

In [15]:
a + b

array([11, 22, 33, 44, 55])

**15. 一维数组减法运算：**

In [16]:
a - b

array([ 9, 18, 27, 36, 45])

**16. 一维数组乘法运算：**

In [17]:
a * b

array([ 10,  40,  90, 160, 250])

**17. 一维数组除法运算：**

In [18]:
a / b

array([10., 10., 10., 10., 10.])

**生成二维示例数组（可以看作矩阵）：**

In [19]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A, B

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

**18. 矩阵加法运算：**

In [20]:
A + B

array([[ 6,  8],
       [10, 12]])

**19. 矩阵减法运算：**

In [21]:
A - B

array([[-4, -4],
       [-4, -4]])

**20. 矩阵元素间乘法运算：**

In [22]:
A * B

array([[ 5, 12],
       [21, 32]])

**21. 矩阵乘法运算（注意与上题的区别）：**

In [23]:
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

如果使用 `np.mat` 将二维数组准确定义为矩阵，就可以直接使用 `*` 完成矩阵乘法计算。

In [24]:
np.mat(A) * np.mat(B)

matrix([[19, 22],
        [43, 50]])

**22. 数乘矩阵：**

In [25]:
2 * A

array([[2, 4],
       [6, 8]])

**23. 矩阵的转置：**

In [26]:
A.T

array([[1, 3],
       [2, 4]])

**24. 矩阵求逆：**

In [27]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### 数学函数

**25. 三角函数：**

In [28]:
print(a)

np.sin(a)

[10 20 30 40 50]


array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

**26. 以自然对数函数为底数的指数函数：**

In [29]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

**27. 数组的方根的运算（开平方）：**

In [30]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

**28. 数组的方根的运算（立方）：**

In [31]:
np.power(a, 3)

array([  1000,   8000,  27000,  64000, 125000], dtype=int32)

### 数组切片和索引

**29. 一维数组索引：**

In [32]:
a = np.array([1, 2, 3, 4, 5])
a[0], a[-1]

(1, 5)

**30. 一维数组切片：**

In [33]:
a[0:2], a[:-1]

(array([1, 2]), array([1, 2, 3, 4]))

**31. 二维数组索引：**

In [34]:
a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
a[0], a[-1]

(array([1, 2, 3]), array([7, 8, 9]))

**32. 二维数组切片（取第 2 列）：**

In [35]:
print(a)

a[:, 1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 5, 8])

**33. 二维数组切片（取第 2，3 行）：**

In [36]:
a[1:3, :]

array([[4, 5, 6],
       [7, 8, 9]])

### 数组形状操作

**生成二维示例数组：**

In [39]:
a = np.random.random((3, 2))
a

array([[0.4555051 , 0.31579443],
       [0.23115345, 0.09173902],
       [0.11568753, 0.131042  ]])

**34. 查看数组形状：**

In [40]:
a.shape

(3, 2)

**35. 更改数组形状（不改变原始数组）：**

In [41]:
a.reshape(2, 3) # reshape 并不改变原始数组

array([[0.4555051 , 0.31579443, 0.23115345],
       [0.09173902, 0.11568753, 0.131042  ]])

In [42]:
a

array([[0.4555051 , 0.31579443],
       [0.23115345, 0.09173902],
       [0.11568753, 0.131042  ]])

**36. 更改数组形状（改变原始数组）：**

In [43]:
a.resize(2, 3) # resize 会改变原始数组

In [44]:
a

array([[0.4555051 , 0.31579443, 0.23115345],
       [0.09173902, 0.11568753, 0.131042  ]])

**37. 展平数组：**

In [45]:
a.ravel()

array([0.4555051 , 0.31579443, 0.23115345, 0.09173902, 0.11568753,
       0.131042  ])

**38. 垂直拼合数组：**

In [46]:
# 生成示例数组
a = np.random.randint(10, size=(3, 3))
b = np.random.randint(10, size=(3, 3))

a, b

(array([[5, 4, 4],
        [7, 7, 4],
        [2, 4, 5]]),
 array([[2, 6, 9],
        [6, 7, 9],
        [8, 1, 8]]))

In [49]:
np.vstack((a, b))

array([[5, 4, 4],
       [7, 7, 4],
       [2, 4, 5],
       [2, 6, 9],
       [6, 7, 9],
       [8, 1, 8]])

**39. 水平拼合数组：**

In [50]:
np.hstack((a, b))

array([[5, 4, 4, 2, 6, 9],
       [7, 7, 4, 6, 7, 9],
       [2, 4, 5, 8, 1, 8]])

**40. 沿横轴分割数组：**

In [51]:
np.hsplit(a, 3)

[array([[5],
        [7],
        [2]]),
 array([[4],
        [7],
        [4]]),
 array([[4],
        [4],
        [5]])]

**41. 沿纵轴分割数组：**

In [52]:
np.vsplit(a, 3)

[array([[5, 4, 4]]), array([[7, 7, 4]]), array([[2, 4, 5]])]

### 数组排序

In [53]:
# 生成示例数组
a = np.array(([1, 4, 3], [6, 2, 9], [4, 7, 2]))
a

array([[1, 4, 3],
       [6, 2, 9],
       [4, 7, 2]])

**42. 返回每列最大值：**

In [54]:
np.max(a, axis=0)

array([6, 7, 9])

**43. 返回每行最小值：**

In [55]:
np.min(a, axis=1)

array([1, 2, 2])

**44. 返回每列最大值索引：**

In [56]:
np.argmax(a, axis=0)

array([1, 2, 1], dtype=int64)

**45. 返回每行最小值索引：**

In [57]:
np.argmin(a, axis=1)

array([0, 1, 2], dtype=int64)

### 数组统计

**46. 统计数组各列的中位数：**

In [59]:
# 继续使用上面的 a 数组
np.median(a, axis=0)

array([4., 4., 3.])

**47. 统计数组各行的算术平均值：**

In [60]:
np.mean(a, axis=1)

array([2.66666667, 5.66666667, 4.33333333])

**48. 统计数组各列的加权平均值：**

In [61]:
np.average(a, axis=0)

array([3.66666667, 4.33333333, 4.66666667])

**49. 统计数组各行的方差：**

In [62]:
np.var(a, axis=1)

array([1.55555556, 8.22222222, 4.22222222])

**50. 统计数组各列的标准偏差：**

In [63]:
np.std(a, axis=0)

array([2.05480467, 2.05480467, 3.09120617])

### 进阶部分

**51. 创建一个 5x5 的二维数组，其中边界值为1，其余值为0：**

In [64]:
Z = np.ones((5, 5))
Z[1:-1, 1:-1] = 0
Z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

**52.使用数字 0 将一个全为 1 的 5x5 二维数组包围：**

In [65]:
Z = np.ones((5, 5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

**53. 创建一个 5x5 的二维数组，并设置值 1, 2, 3, 4 落在其对角线下方：**

In [66]:
Z = np.diag(1+np.arange(4), k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

**54. 创建一个 10x10 的二维数组，并使得 1 和 0 沿对角线间隔放置：**

In [67]:
Z = np.zeros((10, 10), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

**55. 创建一个 0-10 的一维数组，并将 (1, 9] 之间的数全部反转成负数：**

In [69]:
Z = np.arange(11)
Z[(1<Z) & (Z<=9)] *= -1
Z

array([ 0,  1, -2, -3, -4, -5, -6, -7, -8, -9, 10])

**56. 找出两个一维数组中相同的元素：**

In [70]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print('Z1:', Z1)
print('Z2:', Z2)
np.intersect1d(Z1, Z2)

Z1: [7 6 2 0 7 7 2 5 8 7]
Z2: [3 6 6 9 4 5 0 4 1 2]


array([0, 2, 5, 6])

**57. 使用 NumPy 打印昨天、今天、明天的日期：**

In [72]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print('yesterday: ', yesterday)
print('today: ', today)
print('tomorrow: ', tomorrow)

yesterday:  2021-11-03
today:  2021-11-04
tomorrow:  2021-11-05


**58. 使用五种不同的方法去提取一个随机数组的整数部分：**

In [74]:
Z = np.random.uniform(0, 10, 10)
print('原始值：', Z)

print("方法 1：", Z - Z % 1)
print("方法 2：", np.floor(Z))
print("方法 3：", np.ceil(Z) -1 )
print("方法 4：", Z.astype(int))
print("方法 5：", np.trunc(Z))

原始值： [7.76271332 3.39812216 2.95468663 6.69052519 8.63603756 8.27228536
 7.04839721 3.31233426 6.33973927 0.75066298]
方法 1： [7. 3. 2. 6. 8. 8. 7. 3. 6. 0.]
方法 2： [7. 3. 2. 6. 8. 8. 7. 3. 6. 0.]
方法 3： [7. 3. 2. 6. 8. 8. 7. 3. 6. 0.]
方法 4： [7 3 2 6 8 8 7 3 6 0]
方法 5： [7. 3. 2. 6. 8. 8. 7. 3. 6. 0.]


**59. 创建一个 5x5 的矩阵，其中每行的数值范围从 1 到 5：**

In [75]:
Z = np.zeros((5, 5))
Z += np.arange(1, 6)

Z

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])